sources:
    data_dir: '/data/exporter/' # full path to the data file
    output_dir: '/data/exporter/' # full path to output directory
    data_url: 'https://download.bbbike.org/osm/extract/planet_-80.716_0.888_dc4c915d.osm.pbf'
    input_dir: '/data/exporter/'
    filename: 'mapfile.pbf'

admin_levels:
    - 2
    - 4 
    - 6

tolerance: 0.001

country_osm_id: ${COUNTRY_OSM_ID}  # OSM Country Id,

# logging setup
logging:
    version: 1
    disable_existing_loggers: False
    formatters:
        simple:
            format: '%(levelname)s %(message)s'
        verbose:
            format: '%(levelname)s %(asctime)s %(module)s %(message)s'
            datefmt: '%Y/%m/%d %H:%M:%S'

    handlers:
        console:
            class: logging.StreamHandler
            formatter: simple
            level: DEBUG
            stream: ext://sys.stdout
        file:
            class : logging.FileHandler
            formatter: verbose
            level: DEBUG
            mode: w
            filename: /tmp/export.log

    root:
        level: DEBUG
        handlers:
            - console
            - file

